# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add_to_group": "00_LR_BYOL_PRED.ipynb",
         "batchify_data": "00_LR_BYOL_PRED.ipynb",
         "byol_model": "00_LR_BYOL_PRED.ipynb",
         "create_groups": "00_LR_BYOL_PRED.ipynb"}

modules = ["core.py"]

doc_url = "https://HamzaFarhan.github.io/lr_sorting/"

git_url = "https://github.com/HamzaFarhan/lr_sorting/tree/master/"

def custom_doc_links(name): return None
